version: '3'
services:
  mysqld:
    container_name: mysqld
    hostname: mysql
    image: mysql:5.7
    restart: always
    build: ./docker-mysqld57
    environment:
      MYSQL_DATABASE: metabase
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "${MYSQLD_PORT}:3306"
    volumes:
      - ./mysqld-data:/var/lib/mysql

  metabase:
    image: 'metabase/metabase'
    container_name: metabase
    depends_on:
      - mysqld
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: mysqld
    ports:
      - "${METABASE_PORT}:3000"

